library flutter_kurdish_localization_fork;

export 'package:flutter_kurdish_localization_fork/kurdish_cupertino_localization_delegate.dart';
export 'package:flutter_kurdish_localization_fork/kurdish_material_localization_delegate.dart';
export 'package:flutter_kurdish_localization_fork/kurdish_widget_localization_delegate.dart';
