library flutter_kurdish_localization;

export 'package:flutter_kurdish_localization/kurdish_material_localization_delegate.dart';
export 'package:flutter_kurdish_localization/kurdish_widget_localization_delegate.dart';
export 'package:flutter_kurdish_localization/kurdish_cupertino_localization_delegate.dart';
